# Generated by Django 5.0.1 on 2024-01-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kahut", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kahut",
            name="deadline",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="kahut",
            name="finished_ad",
            field=models.DateField(null=True),
        ),
    ]
